import { lazy, Suspense, useLayoutEffect, useRef } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useApp } from '../store.js'
import ToolsMountain from '../components/ToolsMountain.jsx'
import Social from '../components/Social.jsx'
const Scene = lazy(() => import('../components/PortfolioScene.jsx'))
const KW = { en: ['Three.js', 'WebGL2', 'GSAP', 'ScrollTrigger', 'Lenis', 'React', 'Next.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'WordPress', 'WooCommerce', 'MERN', 'e-commerce', 'multilingual translator', 'end-to-end', 'n8n', '3D'],
  fa: ['فول‌استک', 'Three.js', 'WebGL2', 'GSAP', 'ScrollTrigger', 'Lenis', 'React', 'Next.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'وردپرس', 'ووکامرس', 'MERN', 'مترجم چندزبانه', 'فروشگاه اینترنتی', 'n8n', 'سه‌بعدی'] }
const Mark = ({ t, k }) => { const re = new RegExp('(' + k.map(x => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')', 'i'); return t.split(re).map((s, i) => i % 2 ? <mark key={i} className="pf-mark">{s}</mark> : s) }
const PR = [['VÉRION — 3D Luxury Watch Store', 'https://luxrious-watches-orcin.vercel.app'], ['Kabab Dagh Nan Dagh', 'https://kababdagh.com'], ['Bonyan Sazeh Kourosh Kabir', 'https://construction-website-eosin.vercel.app'], ['E-ZONE', 'https://e-zone-app.vercel.app'], ['FitZone', 'https://gym-website-rvhj.vercel.app'], ['Apple-Style E-commerce', 'https://apple-project-flame.vercel.app'], ['LinkedIn Automation', '']]
const D = {
  en: { k: 'PORTFOLIO', name: 'Fatemeh Rostami', role: 'Full-Stack Developer · Interactive 3D Web', intro: 'Interactive Three.js / WebGL2 hero sections and GSAP scroll-driven interfaces for e-commerce, hospitality, medical and enterprise websites.',
    ah: 'About', ab: ['Full-stack developer and multilingual translator specializing in modern, responsive web platforms, with a focus on e-commerce, hospitality and service businesses.', 'Experienced across the MERN stack (React, Next.js, Node.js, MongoDB), PostgreSQL and WordPress/WooCommerce. Projects are delivered end-to-end for clients in Iran and on international freelance platforms, in Persian, English, Arabic and Turkish.'],
    sh: 'Skills', th: 'Tools & technologies', tn: 'Each card opens the tool’s official website.', sk: [['3D & Motion', 'Three.js · WebGL2 · Canvas · GSAP & ScrollTrigger · Lenis · requestAnimationFrame loops'], ['Frontend', 'React · Next.js · Responsive design · Elementor · Dark/Light mode · Reusable components'], ['Backend & Data', 'Node.js · Express · Next.js API routes · MongoDB · PostgreSQL'], ['CMS & Automation', 'WordPress · WooCommerce · n8n · API integrations']],
    ph: 'Selected projects', pd: ['Bilingual (EN/FA) 3D luxury watch store: scroll-driven exploded view with React Three Fiber, product configurator, blog, cart and an Express + PostgreSQL backend.', 'Trilingual restaurant website in Doha with online ordering, catering requests, QR menu and PWA prompts.', 'Next.js and MongoDB corporate site with a CMS admin panel, dark/light theme, RTL/LTR and 360° virtual tours.', 'Bilingual customs, warehouse and production management platform (React, Express, PostgreSQL).', 'Responsive gym platform built around trainee and coach dashboards.', 'Front-end store concept inspired by Apple’s product design language.', 'n8n pipeline: YouTube Data API, Gemini, DALL-E 3, Telegram Bot and Google Sheets.'], visit: 'Visit site',
    eh: 'Experience', ex: ['Freelance Full-Stack Developer & Translator on Freelancer.com, Fiverr, Karlancer and OpenSooq.', 'Interactive 3D hero sections and motion-rich interfaces (Three.js, WebGL2, GSAP, Lenis), optimized for performance.', 'Tiered proposals: WordPress/WooCommerce builds and custom React/Next.js solutions matched to budget.'], lang: 'Languages: Persian (native), English, Arabic, Turkish', ch: 'Let’s work together' },
  fa: { k: 'نمونه‌کار', name: 'فاطمه رستمی', role: 'توسعه‌دهنده‌ی فول‌استک · وب سه‌بعدی تعاملی', intro: 'بخش‌های هیرو تعاملی با Three.js و WebGL2 و رابط‌های اسکرول‌محور با GSAP برای وب‌سایت‌های فروشگاهی، رستورانی، پزشکی و سازمانی.',
    ah: 'درباره‌ی من', ab: ['توسعه‌دهنده‌ی فول‌استک و مترجم چندزبانه، متخصص پلتفرم‌های وب مدرن و ریسپانسیو با تمرکز بر فروشگاه اینترنتی، خدمات و کسب‌وکارهای میزبانی.', 'تجربه در استک MERN (React، Next.js، Node.js، MongoDB)، PostgreSQL و وردپرس/ووکامرس. پروژه‌ها را برای مشتریان ایران و پلتفرم‌های بین‌المللی فریلنسر به فارسی، انگلیسی، عربی و ترکی تحویل می‌دهم.'],
    sh: 'مهارت‌ها', th: 'ابزارها و فناوری‌ها', tn: 'هر کارت وب‌سایت رسمی همان ابزار را باز می‌کند.', sk: [['سه‌بعدی و موشن', 'Three.js · WebGL2 · Canvas · GSAP و ScrollTrigger · Lenis · حلقه‌های requestAnimationFrame'], ['فرانت‌اند', 'React · Next.js · طراحی ریسپانسیو · Elementor · حالت تیره/روشن · کامپوننت‌های قابل‌استفاده‌ی مجدد'], ['بک‌اند و داده', 'Node.js · Express · API Routes در Next.js · MongoDB · PostgreSQL'], ['CMS و اتوماسیون', 'وردپرس · ووکامرس · n8n · یکپارچه‌سازی API']],
    ph: 'پروژه‌های منتخب', pd: ['فروشگاه سه‌بعدی ساعت لوکس دوزبانه (EN/FA): نمای انفجاری اسکرول‌محور با React Three Fiber، کانفیگوراتور محصول، بلاگ، سبد خرید و بک‌اند Express و PostgreSQL.', 'وب‌سایت سه‌زبانه‌ی رستوران در دوحه با سفارش آنلاین، درخواست کترینگ، منوی QR و PWA.', 'وب‌سایت سازمانی با Next.js و MongoDB، پنل ادمین CMS، تم تیره/روشن، RTL/LTR و تور مجازی ۳۶۰ درجه.', 'پلتفرم دوزبانه‌ی مدیریت گمرک، انبار و تولید (React، Express، PostgreSQL).', 'پلتفرم ریسپانسیو باشگاه ورزشی با داشبورد ورزشکار و مربی.', 'نمونه‌ی فروشگاه فرانت‌اند با الهام از زبان طراحی اپل.', 'پایپ‌لاین n8n: YouTube Data API، Gemini، DALL-E 3، ربات تلگرام و Google Sheets.'], visit: 'مشاهده‌ی سایت',
    eh: 'تجربه', ex: ['توسعه‌دهنده‌ی فول‌استک و مترجم فریلنسر در Freelancer.com، Fiverr، کارلنسر و OpenSooq.', 'هیروهای سه‌بعدی تعاملی و رابط‌های پرحرکت (Three.js، WebGL2، GSAP، Lenis) با بهینه‌سازی عملکرد.', 'پیشنهادهای پلکانی: ووکامرس/وردپرس و راه‌حل‌های سفارشی React/Next.js متناسب با بودجه.'], lang: 'زبان‌ها: فارسی (مادری)، انگلیسی، عربی، ترکی', ch: 'بیا با هم کار کنیم' } }
export default function Portfolio() {
  const lang = useApp(s => s.lang), theme = useApp(s => s.theme), d = D[lang], fa = lang === 'fa', root = useRef(), pin = useRef(), track = useRef(), prog = useRef(0)
  useLayoutEffect(() => {
    gsap.registerPlugin(ScrollTrigger); const mm = gsap.matchMedia()
    const ctx = gsap.context(() => {
      mm.add('(min-width: 900px)', () => { const tr = track.current; gsap.to(tr, { x: () => -(tr.scrollWidth - innerWidth + 120), ease: 'none', scrollTrigger: { trigger: pin.current, start: 'top top', end: () => '+=' + tr.scrollWidth, pin: true, scrub: 1, invalidateOnRefresh: true } }) })
      ScrollTrigger.create({ trigger: '.pf-tools', start: 'top 75%', end: 'bottom 25%', onToggle: st => gsap.to('.pf-stage', { opacity: st.isActive ? .1 : 1, duration: .7, ease: 'power2.out', overwrite: true }) })
      ScrollTrigger.batch('.pf-mark', { start: 'top 92%', once: true, onEnter: els => gsap.to(els, { backgroundSize: '100% 100%', duration: .9, stagger: .06, ease: 'power2.out' }) })
      ScrollTrigger.create({ trigger: root.current, start: 'top top', end: 'bottom bottom', scrub: true, onUpdate: s => { prog.current = s.progress } })
      gsap.from('.pf-w > span', { yPercent: 115, opacity: 0, stagger: .12, duration: 1.1, ease: 'power4.out' })
      gsap.from('.pf-hero .pf-in', { y: 30, opacity: 0, stagger: .15, delay: .5, duration: 1, ease: 'power3.out' })
      gsap.utils.toArray('.pf-rv, .pf-j').forEach(el => gsap.from(el, { y: 90, scale: .95, opacity: 0, duration: 1.1, ease: 'back.out(1.8)', scrollTrigger: { trigger: el, start: 'top 90%', once: true } }))
      gsap.from('.pf-sk', { y: 70, scale: .94, opacity: 0, stagger: .12, ease: 'back.out(1.7)', scrollTrigger: { trigger: '.pf-skills', start: 'top 85%', once: true } })
    }, root)
    document.fonts?.ready.then(() => ScrollTrigger.refresh())
    return () => { mm.revert(); ctx.revert() }
  }, [lang])
  return <main className="pf" ref={root}><div className="pf-stage" aria-hidden="true"><Suspense fallback={null}><Scene prog={prog} accent={theme === 'light' ? '#ea580c' : '#c9a96e'} /></Suspense></div>
    <section className="pf-hero"><span className="kicker pf-in">{d.k}</span><h1>{d.name.split(' ').map(w => <span className="pf-w" key={w}><span>{w}</span></span>)}</h1><p className="pf-role pf-in">{d.role}</p><p className="lead pf-in"><Mark t={d.intro} k={KW[lang]} /></p></section>
    <section className="pf-sec"><div className="glass pf-rv pf-about"><figure className="pf-photo"><img src="/images/portfolio/fatemeh-portfolio.webp" alt={d.name} width="600" height="750" loading="lazy" decoding="async" onError={e => { e.currentTarget.parentElement.style.display = 'none' }} /></figure><div><h2>{d.ah}</h2>{d.ab.map((x, i) => <p key={i} className="lead pf-j"><Mark t={x} k={KW[lang]} /></p>)}</div></div></section>
    <section className="pf-sec"><h2 className="pf-rv pf-h2">{d.sh}</h2><div className="pf-skills">{d.sk.map(([a, b]) => <article key={a} className="glass pf-sk"><h3>{a}</h3><p className="lead">{b}</p></article>)}</div></section>
    <ToolsMountain fa={fa} title={d.th} note={d.tn} listLabel={fa ? 'نمایش فهرست کامل' : 'Show the full list'} />
    <section className="pf-pin" ref={pin}><div className="pf-ph"><h2>{d.ph}</h2></div><div className="pf-track" ref={track} style={{ direction: 'ltr' }}>{PR.map(([n, u], i) => <article key={n} className="glass pf-card" style={{ direction: fa ? 'rtl' : 'ltr' }}><span className="kicker">0{i + 1}</span><h3>{n}</h3><p className="lead"><Mark t={d.pd[i]} k={KW[lang]} /></p>{u && <a className="btn" href={u} target="_blank" rel="noopener noreferrer">{d.visit} ↗</a>}</article>)}</div></section>
    <section className="pf-sec"><div className="glass pf-rv"><h2>{d.eh}</h2>{d.ex.map((x, i) => <p key={i} className="lead pf-j"><Mark t={x} k={KW[lang]} /></p>)}<p className="lead"><strong>{d.lang}</strong></p></div></section>
    <section className="pf-sec pf-end"><h2 className="pf-rv pf-h2">{d.ch}</h2><a className="btn fill" href="mailto:fatimarostami963369@gmail.com">fatimarostami963369@gmail.com</a><Social /></section></main>
}
