export const COPY = {
  en: {
    art: ['A mechanical watch has no battery. A coiled mainspring stores energy, a train of gears carries it forward, and the escapement releases it in tiny, exact steps while the balance wheel swings back and forth, typically 28,800 times an hour.', 'The principle has barely changed since the 18th century. What has changed is the precision of manufacture: parts are measured in hundredths of a millimetre.', 'VÉRION exposes that tradition. The skeleton dial lets you read the time and watch the movement that produces it.'],
    exp: ['A watch is built in layers. The sapphire crystal, rated 9 on the Mohs scale of hardness, sits above the hands; below them, bridges and a main plate hold the wheels, each pivoting in synthetic ruby jewels that cut friction.', 'The tourbillon, patented by Abraham-Louis Breguet in 1801, rotates the escapement inside a cage to average out the effect of gravity on accuracy. Keep scrolling to see every layer separate.'],
    prec: ['Cases are offered in 316L stainless steel, grade 5 titanium (roughly 40% lighter than steel) or 18-carat rose gold, an alloy of 75% gold with copper. All are water resistant to 100 metres (10 ATM).', 'The automatic movement stores a 72-hour power reserve, so the watch keeps running through a weekend off the wrist. Every movement is hand-finished with Geneva stripes and perlage on the bridges.'] },
  fa: {
    art: ['ساعت مکانیکی باتری ندارد. یک فنر اصلی انرژی را ذخیره می‌کند، مجموعه‌ای از چرخ‌دنده‌ها آن را منتقل می‌کنند و اسکیپمنت آن را در گام‌های کوچک و دقیق آزاد می‌کند، در حالی که بالانس معمولاً ۲۸٬۸۰۰ بار در ساعت رفت‌وبرگشت می‌کند.', 'این اصل از قرن هجدهم تقریباً تغییر نکرده است. چیزی که عوض شده دقت ساخت است: قطعات با دقت صدم میلی‌متر اندازه‌گیری می‌شوند.', 'ورینون این سنت را نمایان می‌کند. صفحه‌ی اسکلتون هم زمان را نشان می‌دهد و هم موومنتی که آن را می‌سازد.'],
    exp: ['ساعت لایه‌لایه ساخته می‌شود. کریستال یاقوت کبود با سختی ۹ در مقیاس موس بالای عقربه‌هاست؛ زیر آن‌ها پل‌ها و صفحه‌ی اصلی چرخ‌ها را نگه می‌دارند و هر چرخ روی یاقوت مصنوعی می‌چرخد تا اصطکاک کم شود.', 'توربیون که ابراهام-لوئی برگه در سال ۱۸۰۱ ثبت کرد، اسکیپمنت را داخل یک قفس می‌چرخاند تا اثر جاذبه بر دقت میانگین‌گیری شود. اسکرول کن تا همه‌ی لایه‌ها جدا شوند.'],
    prec: ['بدنه در سه جنس موجود است: استیل ۳۱۶L، تیتانیوم درجه ۵ (حدود ۴۰٪ سبک‌تر از استیل) و رزگلد ۱۸ عیار که آلیاژی از ۷۵٪ طلا و مس است. همه تا ۱۰۰ متر ضدآب هستند.', 'موومنت اتوماتیک ۷۲ ساعت ذخیره‌ی انرژی دارد؛ یعنی ساعت یک آخر هفته بدون پوشیدن هم کار می‌کند. هر موومنت با دست و با نقش ژنو و پرلاژ روی پل‌ها تزئین می‌شود.'] } }
