export const API = import.meta.env.VITE_API_URL || '/api'
export const PRODUCTS = [
  { slug: 'aurel', img: '/images/collection/V01-LCC-ROSEE-Packshot-web_2b582d20-07d3-49f7-b6af-a32d1b85ccba.webp', name: 'VÉRION AUREL', name_fa: 'ورینون اورل', price: 4900, c: 'rose', d: 'ivory', s: 'gold', en: 'Rose gold case, ivory dial.', fa: 'بدنه رزگلد با صفحه عاجی.' },
  { slug: 'noir', img: '/images/collection/V0201-TH-CIEL-04_9370b87c-acfb-4327-9854-52391a546911.webp', name: 'VÉRION NOIR', name_fa: 'ورینون نوار', price: 5200, c: 'steel', d: 'obsidian', s: 'black', en: 'Steel case, obsidian dial.', fa: 'بدنه استیل با صفحه سیاه.' },
  { slug: 'chrono', img: '/images/collection/V01-LCC-TEMPETE-Packshot-web_a920f0ec-8a17-4b11-9697-2e4ac6c75ca3.webp', name: 'VÉRION CHRONO', name_fa: 'ورینون کرونو', price: 6400, c: 'titanium', d: 'blue', s: 'white', en: 'Titanium chronograph.', fa: 'کرونوگراف تیتانیوم.' },
  { slug: 'seriex', img: '/images/collection/V0201-TH-AURORE-01.webp', name: 'VÉRION SÉRIE X', name_fa: 'ورینون سری ایکس', price: 7800, c: 'titanium', d: 'obsidian', s: 'black', en: 'Skeleton movement.', fa: 'موومنت اسکلتون.' }]
export const EXTRA = { c: { titanium: 400, steel: 0, rose: 800 }, s: { black: 0, white: 0, gold: 400 } }
export const POSTS = [{ slug: 'movement', title: 'Inside the movement', title_fa: 'درون موومنت', body: 'How a mechanical watch keeps time.', body_fa: 'ساعت مکانیکی چگونه زمان را نگه می‌دارد.' }]
export const T = {
  en: { tag: 'TIME, REFINED.', sub: 'A new expression of mechanical precision.', explore: 'EXPLORE COLLECTION', art: 'ENGINEERED TO BE SEEN.', artd: 'Every component is designed with purpose. VÉRION transforms mechanical engineering into an object of art.', exp: 'Every part, revealed.', col: 'Collection', view: 'View Product', add: 'Add to Cart', cart: 'Cart', blog: 'Journal', account: 'Account', caseL: 'Case', dialL: 'Dial', strapL: 'Strap', checkout: 'Place order', email: 'Email', address: 'Address', pass: 'Password', name: 'Name', login: 'Login', register: 'Register', logout: 'Logout', orders: 'My orders', empty: 'Your cart is empty', ok: 'Order received', spec: ['Automatic movement', '72-hour power reserve', '100m water resistance', 'Sapphire crystal'] },
  fa: { tag: 'زمان، پالایش‌شده.', sub: 'بیانی تازه از دقت مکانیکی.', explore: 'مشاهده کالکشن', art: 'ساخته شده برای دیده شدن.', artd: 'هر قطعه با هدف طراحی شده است. ورینون مهندسی مکانیک را به یک اثر هنری تبدیل می‌کند.', exp: 'هر قطعه، آشکار.', col: 'کالکشن', view: 'مشاهده محصول', add: 'افزودن به سبد', cart: 'سبد خرید', blog: 'مجله', account: 'حساب کاربری', caseL: 'بدنه', dialL: 'صفحه', strapL: 'بند', checkout: 'ثبت سفارش', email: 'ایمیل', address: 'آدرس', pass: 'رمز عبور', name: 'نام', login: 'ورود', register: 'ثبت‌نام', logout: 'خروج', orders: 'سفارش‌های من', empty: 'سبد خرید خالی است', ok: 'سفارش ثبت شد', spec: ['موومنت اتوماتیک', '۷۲ ساعت ذخیره انرژی', 'ضد آب تا ۱۰۰ متر', 'کریستال یاقوت کبود'] } }

export const BANNER = '/images/collection/Eclat_1st_Set-02.webp'
